spring:
  application:
    name: co-mu-nity
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update  # ?? ??????? ????? ???? ????
    show-sql: true      # SQL ?? ?? ???
    properties:
      hibernate:
        format_sql: true   # ??? ?? ?? ??